---
#
# Installing Kibana
#

# Install Kibana 

- name: Install Kibana with apt
  apt:
    name: kibana={{ role_kibana_version }}
    update_cache: yes
 
# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: {{ role_kibana_server_host }}'

- name: Defining server port
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: {{ role_kibana_server_port }}'
    
- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.url:'
   line: "elasticsearch.url: {{ role_kibana_elasticsearch_url }}"
   
# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
