---
- name: update all packages
  yum:
    name: "*"
    state: latest
    exclude: docker-ce,docker-engine,docker-engine-selinux
  when: os_system_updates

- name: install system utilities
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tar
    - xz
    - unzip
    - curl
    - ipset
    - ntp
    - firewalld
    - dnsmasq
    - yum-utils
    - net-tools
    - bind-utils

- name: disable selinux
  selinux: policy=targeted state=permissive

- name: create group 'nogroup'
  group: name=nogroup state=present

- name: ensure ipv6 is not disabled
  sysctl: name={{ item }} value=0 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: enable ntpd
  service:
    name: ntpd
    enabled: yes
    state: started

- name: disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: disable dnsmasq
  service:
    name: dnsmasq
    enabled: no
    state: stopped
