---
# This playbook installs all nodes

- name: create temporary install directory
  file: path={{ dcos_path_tmp }} state=directory mode=0755

- name: download installation file from the bootstrap
  get_url: url="http://{{ dcos_bootstrap_ip }}:{{ dcos_port_webserver }}/dcos_install.sh" dest={{ dcos_path_tmp }}/dcos_install.sh mode=0440 force=yes

- name: check if already installed
  find:
    paths: /opt/mesosphere
    file_type: any
    patterns: "*"
  register: currently_installed

- name: install master
  shell: bash dcos_install.sh master
  args:
    chdir: "{{ dcos_path_tmp }}"
  when:
    - currently_installed.matched|int == 0
    - "'masters' in group_names"

- name: install agent
  shell: bash dcos_install.sh slave
  args:
    chdir: "{{ dcos_path_tmp }}"
  when:
    - currently_installed.matched|int == 0
    - "'agents' in group_names"

- name: install public agent
  shell: bash dcos_install.sh slave_public
  args:
    chdir: "{{ dcos_path_tmp }}"
  when:
    - currently_installed.matched|int == 0
    - "'agent_publics' in group_names"
