---
#
# Installing Logstash
#

- name: Install base packages
  apt:
    name: logstash
    update_cache: yes

- name: example copying file with owner and permissions
  copy:
    src: "{{ role_logstash_src }}"
    dest: "{{ role_logstash_dest }}"
    owner: "{{ user }}"
    mode: "{{ role_logstash_mode }}"

- name: Start service logstash , if not running
  service:
     name: logstash
     state: started

