---
- name: Install base packages
  apt: name={{ item }} state=installed
  with_items:
    - logstash
  tags:
    - packages  
  
- name: example copying file with owner and permissions
  copy:
    src: ../install/roles/logstash/templates/apache-01.conf
    dest: /etc/logstash/conf.d/apache-01.conf
    owner: vagrant
    mode: 0644  

- name: Start service logstash , if not running
  service:
     name: logstash
     state: started

