---
# This playbook installs docker

- name: enable overlay module
  lineinfile:
    dest: /etc/modules-load.d/overlay.conf
    state: present
    create: yes
    line: 'overlay'

- name: load overlay module
  modprobe:
    name: overlay
    state: present

- name: enable docker yum repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  changed_when: false

- name: create docker systemd directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: 0755

- name: configure docker to use overlay driver
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0644
    force: yes
  notify:
    - restart docker

- name: install docker packages
  yum:
    name: "docker-ce-{{ docker_version }}"
    update_cache: yes
    state: present

- name: enable docker
  service:
    name: docker
    enabled: yes
    state: started

- name: allow the default user to use docker
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
