---
# This playbook manages Kubernetes on DC/OS as a service

- name: install kubernetes
  include_tasks: kubernetes.yml
  when: dcos_k8s_enabled

- name: install kubernetes proxy
  include_tasks: kubernetes-proxy.yml
  when: dcos_k8s_enabled

- name: connect kubectl
  include_tasks: kubectl.yml
  when: dcos_k8s_enabled

- pause:
    minutes: 4

- name: run flink
  include_tasks: flink.yml
