---
# This playbook uninstalls kubernetes on DC/OS as a service

- name: uninstall kubernetes
  dcos_package:
    name: kubernetes
    app_id: "{{ dcos_k8s_app_id }}"
    version: "{{ dcos_k8s_package_version }}"
    state: absent

- name: uninstall kubernetes-proxy
  dcos_marathon:
    app_id: "{{ dcos_k8s_proxy_app_id }}"
    state: absent
  ignore_errors: true

- name: delete the kubectl executable
  become: false
  file:
    path: '../kubectl'
    state: absent
