Vagrant.configure("2") do |config|

  config.vm.define "saas-pro" do |pro|
    pro.vm.box = "ubuntu/trusty64"
    pro.vm.hostname = "saas-pro"
    pro.vm.network "forwarded_port", guest: 9092, host:9092
    pro.vm.network "private_network", ip: "192.168.33.30"

    pro.vm.provider :virtualbox do |vb|
      vb.name = "saas-pro"
      vb.memory = "8192"
      end

    config.vm.provision "ansible" do |ansible|
      ansible.galaxy_roles_path = "install/roles/"
      ansible.playbook = "tasks/main.yml"
    end

  end
end
