---
# This playbook upgrades all nodes

- name: create temporary install directory
  file: path={{ dcos_path_tmp }} state=directory mode=0755

- name: download installation file from the bootstrap
  get_url: url="http://{{ dcos_bootstrap_ip }}:{{ dcos_port_webserver }}/upgrade/latest/dcos_node_upgrade.sh" dest={{ dcos_path_tmp }}/dcos_node_upgrade.sh mode=0440 force=true

- import_tasks: master.yml
  when: "'masters' in group_names"

- import_tasks: agent.yml
  when: "'agents' in group_names"

- import_tasks: agent.yml
  when: "'agent_publics' in group_names"
