---
- name: install packages
  hosts: localhost
  serial: 1
  become: false
  environment:
    PATH: '{{ ansible_env.PATH }}:{{ ansible_env.PWD }}/..'


  roles:
    - package

  tasks:

    - name: ensure elastic is installed
      when: (role_install_elastic)
      dcos_package:
        name: elastic
        state: present
        version: "{{ elastic_version }}"
        options: 
          master_nodes: 
            cpus: "{{ elastic_options_master_nodes_cpus }}"
            mem: "{{ elastic_options_master_nodes_mem }}"
            heap: 
              size: "{{ elastic_options_master_nodes_heap_size }}"
          data_nodes: 
            count: "{{ elastic_options_data_nodes_count }}"
            cpus: "{{ elastic_options_data_nodes_cpus }}"
            mem: "{{ elastic_options_data_nodes_mem }}"
            heap: 
              size: "{{ elastic_options_data_nodes_heap_size }}"
          coordinator_nodes: 
            count: "{{ elastic_options_coordinator_nodes_count }}"
            cpus: "{{ elastic_options_coordinator_nodes_cpus }}"
            mem: "{{ elastic_options_coordinator_nodes_mem }}"
            heap: 
              size: "{{ elastic_options_coordinator_nodes_heap_size }}"


    - name: ensure kafka is installed
      when: (role_install_kafka)
      dcos_package:
        name: kafka
        state: present
        version: "{{ kafka_version }}"
        options: 
          brokers: 
            count: "{{ kafka_options_brokers_count }}"
            cpus: "{{ kafka_options_brokers_cpus }}"
            mem: "{{ kafka_options_brokers_mem }}"
          kafka:
            offsets_topic_replication_factor: "{{ kafka_options_brokers_kafka_offsets }}"
       
    - name: ensure logstash is installed
      when: (role_install_logstash)
      dcos_package:
        name: logstash
        state: present
        version: "{{ logstash_version }}"
        options: 
          logstash:
            config-string: "{{ logstash_options_logstash_config_string }}"
            instances: "{{ logstash_options_logstash_instances }}"

    - name: ensure kibana is installed
      when: (role_install_kibana)
      dcos_package:
        name: kibana
        state: present
        version: "{{ kibana_version }}"
        options: 
          kibana: 
            elasticsearch_url: "{{ kibana_options_kibana_elasticsearch_url }}"
            cpus: "{{ kibana_options_kibana_cpus }}"
            mem: "{{ kibana_options_kibana_mem }}"

    
    - pause:
        minutes: 4

    
