---
# this playbook manages DC/OS CLI

- name: Check if DC/OS CLI is already installed
  become: false
  find:
    paths: '..'
    file_type: file
    patterns: 'dcos'
  register: dcos_cli_installed
  when: dcos_cli_enabled

- name: Setup DC/OS CLI
  when: (dcos_cli_enabled and dcos_cli_installed.matched|int == 0) or dcos_cli_upgrade
  block:
    - name: Download the DC/OS CLI Linux binary (dcos) to your current directory and make it executable
      become: false
      get_url: url="https://downloads.dcos.io/binaries/cli/linux/x86-64/dcos-{{ dcos_version | regex_replace('^([0-9]{1,2}\\.[0-9]{1,2})(.*)$', '\\1') }}/dcos" dest="../dcos" mode=0755 force=yes
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Download the DC/OS CLI Darwin binary (dcos) to your current directory and make it executable
      become: false
      get_url: url="https://downloads.dcos.io/binaries/cli/darwin/x86-64/dcos-{{ dcos_version | regex_replace('^([0-9]{1,2}\\.[0-9]{1,2})(.*)$', '\\1') }}/dcos" dest="../dcos" mode=0755 force=yes
      when: ansible_os_family == "Darwin"

- name: Uninstall DC/OS CLI
  become: false
  file:
    path: '../dcos'
    state: absent
  when: not dcos_cli_enabled

- name: Connect to DC/OS cluster
  dcos_connection:
    url: "https://{{ groups['webservers'][0] }}"
    insecure: true
