---
# This playbook runs flink job  in a kubernetes cluster

- name: copy jar file to the container
  command: bash -c 'kubectl cp {{ jar_project_path }}{{jar_project_name}} default/$(kubectl get pods --all-namespaces -owide | grep jobmanager | tr -s " " | cut -d" "  -f2):/tmp'

- name: run flink job
  command: bash -c 'kubectl exec -it $(kubectl get pods --all-namespaces -owide | grep jobmanager | tr -s " " | cut -d" " -f2) flink run /tmp/{{ jar_project_name }} &'

