---
# This playbook upgrades the master nodes

- name: upgrade node
  shell: "bash dcos_node_upgrade.sh"
  args:
    chdir: "{{ dcos_path_tmp }}"
  ignore_errors: yes

- name: wait for mesos master
  wait_for:
    host: "{{ ansible_default_ipv4['address'] }}"
    port: 5050
    delay: 5

- name: check if mesos master recovered
  uri: url=http://{{ ansible_default_ipv4['address'] }}:5050/metrics/snapshot return_content=true
  register: response
  until: "'registrar\\/log\\/recovered\":1.0' in response.content"
  retries: 12
  delay: 5
  changed_when: false
  when: dcos_ee_security != "strict"
